apiVersion: v1
kind: Service
metadata:
  name: elveslibraryapp-active-service
spec:
  type: NodePort
  selector:
    app: elveslibraryapp
  ports:
    - port: 80
      targetPort: 9080
      nodePort: 32100
