- name: Set cluster.
  hosts: Kubernetes_Servers
  tasks:
    - name: Generate join token.
      shell: kubeadm token create --print-join-command
      register: join_command
      when: ansible_host == '{{ ip_master }}'
    - name: Copy join command to file.
      copy: content="{{ join_command.stdout_lines[0] }}" dest="/opt/join-command.sh"
      when: ansible_host == '{{ ip_master }}'
    - name: Pull join command from master.
      fetch:
        src: /opt/join-command.sh
        dest: /opt/join-command.sh
        flat: yes
      when: ansible_host == '{{ ip_master }}'
    - name: Copy join command to Slave1.
      copy:
        src: /opt/join-command.sh
        dest: /opt/join-command.sh
        mode: 0777
      when: ansible_host == '{{ ip_slave1 }}'
    - name: Copy join command to Slave2.
      copy:
        src: /opt/join-command.sh
        dest: /opt/join-command.sh
        mode: 0777
      when: ansible_host == '{{ ip_slave2 }}'
    - name: Join Slave1 to cluster.
      command: sh /opt/join-command.sh
      when: ansible_host == '{{ ip_slave1 }}'
    - name: Join Slave2 to cluster.
      command: sh /opt/join-command.sh
      when: ansible_host == '{{ ip_slave2 }}'
