- name: Install Docker.
  hosts: Docker_Servers
  tasks:
    - name: Place daemon.json
      template:
        src: /opt/IAC_role/templates/daemon.json
        dest: /etc/docker/daemon.json
    - name: Create secret for Nexus.
      shell: kubectl create secret docker-registry nexus --docker-server={{ nexus_ip.stdout_lines[0] }}:8083 --docker-username=admin --docker-password=password
      when: ansible_host == '{{ ip_master }}'
    - name: Install Docker.
      command: "{{ item }}"
      with_items:
          - dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
          - dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm -y
          - dnf install docker-ce --nobest -y
    - name: Start Docker service.
      service:
        name: docker
        state: started
        enabled: yes
