- name: Install Nexus
  hosts: Nexus_Server
  tasks:
    - name: Install OpenJDK 8, wget and bind-utils.
      dnf:
        name:
          - java-1.8.0-openjdk
          - wget
          - bind-utils
    - name: Download latest Nexus package.
      get_url:
       url: "https://download.sonatype.com/nexus/3/nexus-3.30.1-01-unix.tar.gz"
       dest: /opt/nexus-3.30.1-01-unix.tar.gz
    - name: Unarchive Nexus package.
      unarchive:
       src: /opt/nexus-3.30.1-01-unix.tar.gz
       dest: /opt
       remote_src: yes
    - name: Place nexus.service
      template:
        src: /opt/IAC_role/templates/nexus.service
        dest: /etc/systemd/system/nexus.service
    - name: Start Nexus service.
      service:
        name: nexus
        state: started
        enabled: yes
