- name: Install Nexus
  hosts: Nexus_Server
  tasks:
    - name: Install OpenJDK 8 and wget.
      dnf:
        name:
          - java-1.8.0-openjdk
          - wget
    - name: Download latest Nexus package.
      get_url:
       url: "https://download.sonatype.com/nexus/3/nexus-3.30.1-01-unix.tar.gz"
       dest: /opt/nexus-3.30.1-01-unix.tar.gz
    - name: Unarchive Nexus package.
      unarchive:
       src: /opt/nexus-3.30.1-01-unix.tar.gz
       dest: /opt
       remote_src: yes
    - name: Place nexus.service
      template:
        src: /opt/IAC_role/templates/nexus.service
        dest: /etc/systemd/system/nexus.service
    - name: Start Nexus service.
      service:
        name: nexus
        state: started
        enabled: yes
    - name: Register external ip address.
      shell: dig +short myip.opendns.com @resolver1.opendns.com
      register: nexus_ip
    - name: Place daemon.json
      template:
        src: /opt/IAC_role/templates/daemon.json
        dest: /etc/docker/daemon.json
      when: ansible_host == '{{ ip_master }}'
    - name: Place daemon.json
      template:
        src: /opt/IAC_role/templates/daemon.json
        dest: /etc/docker/daemon.json
      when: ansible_host == '{{ ip_slave1 }}'
    - name: Place daemon.json
      template:
        src: /opt/IAC_role/templates/daemon.json
        dest: /etc/docker/daemon.json
      when: ansible_host == '{{ ip_slave2 }}'
    - name: Create secret for Nexus.
      shell: kubectl create secret docker-registry nexus --docker-server={{ nexus_ip.stdout_lines[0] }}:8083 --docker-username=admin --docker-password=password
      when: ansible_host == '{{ ip_master }}'
